### ISSUE TITLE
the curl object return empty response because of https

### ISSUE THREAD

**Issue by Adidi** [macuenca/Instagram-PHP-API#8]
I guess it's not happened to everyone if i don't see this comment till now
I work on my local windows 7 machine with apache.
since every call to instagram API is in https protocol u have to put the curl flag CURLOPT_SSL_VERIFYPEER set to false:
in "_setOptions" function:
curl_setopt($this->handler, CURLOPT_SSL_VERIFYPEER, false);

This solves the problem for local testing use.

**Comment by adrianosmateus** [comment]
Thank you. Your explanation did help me so much!
